apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: go-api-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-api-demo
  template:
    metadata:
      labels:
        app: go-api-demo
    spec:
      containers:
      - name: go-api-demo
        image: lcostea/go-api-demo:0.1.0