apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-app
  labels:
    app.kubernetes.io/name: node-hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: node-hello-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-hello-app
    spec:
      containers:
      - name: node-hello-app
        image: lcostea/node-hello-app:v0.1.0
        ports:
        - containerPort: 3000
          name: http
