apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-demo
  labels:
    app.kubernetes.io/name: go-api-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: go-api-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-api-demo
    spec:
      containers:
      - name: go-api-demo
        image: lcostea/go-api-demo:0.1.0
        ports:
        - containerPort: 3000
          name: http