apiVersion: v1
kind: Service
metadata:
  name: go-api-demo-clusterip
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: go-api-demo
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000