apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-api-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-api-demo
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30