apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-configmap
  labels:
    app: node-configmap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-configmap
  template:
    metadata:
      labels:
        app: node-configmap
    spec:
      containers:
      - name: node-configmap
        image: lcostea/node-configmap:v0.1.0
        env:
        - name: CONNECTION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: node-configmap
              key: connectionTimeout
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: node-configmap
              key: log_level
