apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-liveness-readiness
  labels:
    app: node-liveness-readiness
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-liveness-readiness
  template:
    metadata:
      labels:
        app: node-liveness-readiness
    spec:
      containers:
      - name: node-liveness-readiness
        image: lcostea/node-liveness-readiness:v0.1.0
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /healthy
            port: 3000
