apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-demo-startup
  labels:
    app: go-api-demo-startup
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-api-demo-startup
  template:
    metadata:
      labels:
        app: go-api-demo-startup
    spec:
      containers:
      - name: go-api-demo
        image: lcostea/go-api-demo:0.1.0
        livenessProbe:
          httpGet:
            path: /healthy
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 2
        startupProbe:
          httpGet:
            path: /healthy
            port: 3000
          failureThreshold: 10
          periodSeconds: 5
          timeoutSeconds: 2